name: Flutter Action

on:
  push:
    branches:
      - master

  schedule:
    - cron: "*/10 * * * 0-6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'

      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

    name: Send email
    uses: dawidd6/action-send-mail@v3.7.1
    with:
      server_address: vikasmalavath00@gmail.com
      server_port: 465
      subject: Github Action Email Forwarding
      to: weakass75@gmail.com
      from: Vikas Malavath